CREATE TABLE `t1` (
  `id` INT(11) NOT NULL COMMENT 'ID',
  `name` VARCHAR(255) NOT NULL,
  `age` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=UTF8MB4;
CREATE TABLE `t2` (
  `id` BIGINT(20) NOT NULL,
  `course` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=UTF8MB4;
